version: "3.9"
services:
  api:
    container_name: api
    build: .
    ports:
      - "5000:5000"
    environment:
      GRB_WLSACCESSID: 488ed8bb-6465-44d8-b661-f50a6a34cb5d
      GRB_WLSSECRET: 4a6023ff-12f1-4c66-a160-ecaff37c938c
      GRB_LICENSEID: 925406
    volumes:
      - .:/app
  web_frontend:
    container_name: web-frontend
    # image: cvrp-front
    build:
      context: ../cvrp-front
    ports:
      - "8080:8080"